<?=$this->doctype()?>
<html class="h-100" data-bs-theme="dark" lang="en">
    <head>
        <base href="/" />
        <meta charset="utf-8" />
        <?=$this->headTitle($this->config('app_settings')['site']['title'] ?? '')->setSeparator(' -')->setAutoEscape(false) ?>
        <?php
        $this->headMeta()
        ->appendName('description', $this->config('app_settings')['site']['description'] ?? 'Default description')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headMeta();
        ?>
        <?=$this->headLink(
            [
                'rel'  => 'icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath('assets/img/favicon.ico'),
            ]
            )->appendStylesheet($this->basePath('assets/css/bootstrap.min.css'))
             ->appendStylesheet($this->basePath('assets/css/style.css'))
        ?>
    </head>
    <body class="d-flex flex-column h-100">
        <nav class="navbar navbar-expand-lg mt-0">
            <div class="container rounded bg-body-tertiary shadow-sm">
                <div class="navbar-brand" href="#">
                    <span class="fs-1 fw-bold">Twitch</span>
                </div>
                <ul class="navbar-nav ml-auto">
                    <?php
                    /**
                     * @see App\View\MenuHelper
                     * the array is how you order the menu items
                     */
                    echo $this->menu(['home', 'profile', 'contact'])?>
                </ul>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="row mx-auto">
                        <div class="col">
                        Header Content
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <main class="flex-shrink-0 mt-5 mb-5">
            <div class="container">
                <div class="card">
                    <div class="card-header">
                    </div>
                    <div id="app-workspace" class="card-body">
                        <?=$this->content?>
                    </div>
                </div>
            </div>
        </main>
        <footer class="footer mt-auto">
            <div class="container pb-3 rounded-top bg-body-tertiary">
                <div class="row pt-2">
                    <div class="col">
                        &copy; <?=date('Y') . ' ' . $this->config('app_settings')['site']['copyright']?>
                    </div>
                </div>
            </div>
        </footer>
        <script src="/assets/js/jquery-3.6.4.js"></script>
        <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
        <script src="/assets/js/bootstrap.js"></script>
        <script src="/assets/js/pubsub.js"></script>
        <script src="/assets/js/app.js"></script>
    </body>
</html>